### ISSUE TITLE
Token doesnt get verified and i totally dont know why :(

### ISSUE THREAD

**Issue by blackchain-dev** [cardano-foundation/cardano-token-registry#2212] opened 2022-07-06 14:39 UTC
https://cardanoassets.com/asset1crnqurt6yunp9s08dmvzkpwquvqc5cwdpqy2ug - it shows that metadata is not registered
https://tokens.cardano.org/metadata/1d941951b4cb5b9bfea53ab69080b61aa8fbdb5fa13029fc8c67122f5354414441 - i have triple checked - seems everything is fine

Can somebody explain me what is wrong?

**Comment by cleanerm5** [comment] 2022-07-06 14:49
Hi @blackchain-dev 

the subject is wrong. We had this issue that the policy and subject did not match and in the end we replaced the subject with a policy id that fit the value of the "policy" field. Let me take a look into it and I'll come back to you asap.

**Comment by cleanerm5** [comment] 2022-07-06 15:03
On it in PR #2213 

Issue is that actually you did specify the correct policyid (which is the first 28 bytes or 56 chars of the subject) in your first commits but somehow the CBOR hex value given in the policy field does not hash to the correct policy id meaning that the policy field is somewhat corrupt. I'll get back to you as soon as I figured that out.

**Comment by Rayvid** [comment] 2022-07-06 15:13
Ok, thanks, i think problem is in policy.json file I used then, I think i did smth wrong in the minting process. Can it be the reason?

**Comment by cleanerm5** [comment] 2022-07-06 15:30
The CBOR hex value given in the policy field is wrong. Maybe you changed the minting policy.json after you did the actual minting and before you did generate the metadata files with the token-metadata-creator tools?

The policy CBOR hex string that fits the minting policy recorded on chain is
`82008200581cd459b7f853bff205d701f97b0b4513138c3b86ebce92eb88743e81b2`

Which differs only slightly from the one you provided with the metadata in your PR `82008201818200581cd459b7f853bff205d701f97b0b4513138c3b86ebce92eb88743e81b2`

So the policy.json used for the actual mint accords to:
`{
    "keyHash": "d459b7f853bff205d701f97b0b4513138c3b86ebce92eb88743e81b2",
    "type": "sig"
}`

while the one used within your commits accords to
`{
    "scripts": [
        {
            "keyHash": "d459b7f853bff205d701f97b0b4513138c3b86ebce92eb88743e81b2",
            "type": "sig"
        }
    ],
    "type": "all"
}`

If ok for you I will merge #2213 because it has been validated successfully and the signatures/keys used for signing are the right ones.

**Comment by Rayvid** [comment] 2022-07-06 15:34
Thanks, much appreciated, not sure why i got this "scripts" object key, anyway you save my day! Much appreciated!

**Comment by cleanerm5** [comment] 2022-07-06 16:33
So there still remains an issue with the subject. In the minting process you called the asset "STADA" but the current subject would only work if the asset would be called "ADAStake". The explorers usually look up the minting transactions that are recorded on chain, fetch the policy id from them and the asset name and then do the look-up in the registry. So for your metadata they still will not be able to find it because the subject is slightly wrong and this time I cannot help you because when I change the subject also the signing needs to be done again (as the signature is computed from the subject, property-name, sequence-number and the actual value).

This means you must again sign the metadata file with your policy keys. Just make sure that the value in the `policy` field is `82008200581cd459b7f853bff205d701f97b0b4513138c3b86ebce92eb88743e81b2` and the subject should be `8a60b9a2aeb22c0f0a2a70cac8cd16dd99dc0542a31f3bc075551be35354414441` meaning that also the file must be called `8a60b9a2aeb22c0f0a2a70cac8cd16dd99dc0542a31f3bc075551be35354414441.json`

Quite a journey. Sorry for the circumstances.

**Comment by Rayvid** [comment] 2022-07-07 04:54
Thanks, i think i got it right this time https://github.com/cardano-foundation/cardano-token-registry/pull/2216

**Comment by cleanerm5** [comment] 2022-07-08 07:38
I close this one as also [cardanoassets](https://cardanoassets.com/asset1crnqurt6yunp9s08dmvzkpwquvqc5cwdpqy2ug) does display the metadata as intended.

**Closed by cleanerm5** 2022-07-08 07:38 UTC
